### ISSUE TITLE
Story menu assets do not properly convert

### ISSUE THREAD

**Issue by Rev2-Git** [gusborg88/fnf-porter#22]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Full mod

### What is missing?

The story menu doesn’t load week image assets, causing the game to display the flixel logos commonly seen with sprites that can’t be found. It also seems to crash when hovering over certain weeks, but I’m not sure what the pattern there is.

### Missing files checklist

- [X] I have checked the converter supports these files
- [X] I have checked both directories, the original and converted one, and they aren't in the converted one

**Comment by VocalFan** [comment]
I've found that the logo issue is because the Psych Engine version's week,json... The converter reads the weekName value, which for me... Was

`"weekName": "Updike"`

When the week is actually called Facility in the files (the week json and png)

So instead of being called `"titleAsset": "storymenu/titles/Updike",` it should be `"titleAsset": "storymenu/titles/facility",`

**Comment by tposejank** [comment]
Noted. This was also a problem while testing
